### ISSUE TITLE
opusのURL更新のお願い

### ISSUE THREAD

**Issue by flll** [TumoiYorozu/DiscordWerewolf.ts#32]
# npm instal 途中にエラーが発生
discordjs/opusのURLが存在しないのでダウンロードができずに失敗します
修正をお願いします

> https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-musl-1.2.2.tar.gz

エラー詳細↓
<details>

```npm
# npm install
npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
npm ERR! code 1
npm ERR! path /DiscordWerewolf.ts/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2/opus.node --module_name=opus --module_path=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.4
npm ERR! node-pre-gyp info using node@16.9.1 | linux | x64
npm ERR! node-pre-gyp info check checked for "/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2/opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-musl-1.2.2.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-musl-1.2.2.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.8.0 and node@16.9.1 (node-v93 ABI, musl) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-musl-1.2.2.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.15 found at "/usr/bin/python3"
npm ERR! gyp http GET https://unofficial-builds.nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
npm ERR! gyp http 200 https://unofficial-builds.nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
npm ERR! gyp http GET https://unofficial-builds.nodejs.org/download/release/v16.9.1/SHASUMS256.txt
npm ERR! gyp http 200 https://unofficial-builds.nodejs.org/download/release/v16.9.1/SHASUMS256.txt
npm ERR! (node:276) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/DiscordWerewolf.ts/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.9.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.9.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.9.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/DiscordWerewolf.ts/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | linux | x64
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2/opus.node" "--module_name=opus" "--module_path=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /DiscordWerewolf.ts/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2/opus.node --module_name=opus --module_path=/DiscordWerewolf.ts/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-musl-1.2.2 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/DiscordWerewolf.ts/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/DiscordWerewolf.ts/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /DiscordWerewolf.ts/node_modules/@discordjs/opus
npm ERR! node-pre-gyp ERR! node -v v16.9.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.4
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-12T18_46_00_296Z-debug.log
```

</details>

**Comment by TumoiYorozu** [comment]
WSL Ubuntu18.04, node v16.9.1 環境で `$ npm install` しても正常に終了したのですが、環境とコマンドを教えていただけますか？
（また、もし修正方法のアイディアがあれば、それも一緒に教えていただけると幸いです）

**Comment by flll** [comment]
ご回答大変感謝いたします
返信が遅れてしまい大変申し訳ありません

alpineでビルドしたところ単にライブラリ不足でこのようなエラーが発生してしまいました
g++, make等をインストールしましたところ、無事ビルドに成功いたしました
使用したDockerfileです
大変ご迷惑おかけしました...

<details>
 <summary>Dockerfile</summary>

```

FROM node:16.9.1-alpine AS b

EXPOSE 1072

RUN apk update; \
    apk add ffmpeg=4.3.3-r0 \
        git=2.30.6-r0 \
        python3=3.8.15-r0 \
        make=4.3-r0 \
        g++=10.2.1_pre1-r3
RUN npm install -g typescript@4.7.4

RUN git clone https://github.com/TumoiYorozu/DiscordWerewolf.ts.git
WORKDIR /DiscordWerewolf.ts/
COPY media/dova_syndrome_BGMs media/dova_syndrome_BGMs
COPY server_settings/dova_syndrome_BGMs.txt server_settings/

RUN npm install
RUN tsc
RUN cd media/dova_syndrome_BGMs ; \
    for a in $(ls -1 *.mp3 | sed -e 's>.mp3>>') ;do \
        ffmpeg -y -i ${a}.mp3 -ar 48000 ${a}.wav; \
    done

CMD ["/usr/local/bin/node build/index.js -s server_settings/dova_syndrome_BGMs.txt"]

#FROM node:16.9.1-alpine
#
#WORKDIR /DiscordWerewolf.fs
#COPY --from=b /DiscordWerewolf.ts/package*.json ./
#COPY --from=b /DiscordWerewolf.ts/tsconfig.json ./
#COPY --from=b /DiscordWerewolf.ts/node_modules/ node_modules/
#COPY --from=b /DiscordWerewolf.ts/server_settings/ server_settings/
#COPY --from=b /DiscordWerewolf.ts/media/dova_syndrome_BGMs/*.wav media/dova_syndrome_BGMs
#COPY --from=b /DiscordWerewolf.ts/build/ build/
#COPY --from=b /DiscordWerewolf.ts/src/ src/
#
#CMD ["/usr/local/bin/node build/index.js -s server_settings/dova_syndrome_BGMs.txt"]

# 現在DOVAにて直リンクでのダウンロードが禁止されているため下記リンクからDLをお願いします
# https://dova-s.jp/_contents/agreement/
# ./media/dova_syndrome_BGMs にmp3ファイルをインストール
# https://github.com/TumoiYorozu/DiscordWerewolf.ts/blob/master/misc_tools/setFreeBGM/README.md#使用音源
# ./server_settings/dova_syndrome_BGMs.txt 音楽ファイルをどの効果音にするかをjsonで記述する(.wavで記述すること)
# https://github.com/TumoiYorozu/DiscordWerewolf.ts/wiki/インストール方法#音楽の設定
# $ nerdctl build -t discordwerewolf .
# 
# ./dw_env.txt に環境変数を記述
# $ nerdctl run -it --rm --env-file=dw_env.txt -p 1072:1072 discordwerewolf

```

</details>
